### ISSUE TITLE
Is there any way to get multiple dividers?

### ISSUE THREAD

**Issue by McBobb** [freaktechnik/divider#2]
There used to be multiple versions of an addon to add divider lines to the toolbar/overflow menu, allowing for up to 5 dividing lines. As much as this addon is appreciated, there is a need for the ability to add more than one divider for some people to divide addons into multiple groups.

Is there any way to do that with this addon?

**Comment by freaktechnik** [comment]
Any extension can only provide one toolbar button (which is what this extension is doing to create the divider). As such the only way to get extra dividers is to have other extensions that provide a divider.

**Comment by bughit** [comment]
@freaktechnik You could release some number (within reason) of clones of this extension (divider1, divider2, divider3)

**Comment by freaktechnik** [comment]
Sure, I could, but I personally don't have the need and the code is right here, so feel free to do so as long as it's respecting the license!
